### ISSUE TITLE
❔ Miscellaneous

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/github-importer-test#61]
<div align='justify'>This is a collection issue for all types of tasks. Here we will collect tagging ideas that are not yet relevant enough to varant a whole issue.</div>

## Open tasks and potential new issues

- [ ] Rework point and click (input functionality)
- [ ] Revisit _accusation_ (Origin: #24)
- [ ] Revisit _queue_ (Origin: #25)
- [ ] Revisit _automation_ (Origin: #26)
- [ ] Revisit _contradiction_ (Origin: #33)
- [ ] Aussichtspunkte (might be part of motivations) (@rwarnking)
- [ ] level editor (@rwarnking)
- [ ] mod support (@rwarnking)
- [ ] bonuslevel ([Plants vs. Zombies GOTY Edition](https://store.steampowered.com/app/3590/Plants_vs_Zombies_GOTY_Edition/), [Super Meat Boy](https://store.steampowered.com/app/40800/Super_Meat_Boy/)) (Origin: #45) (@rwarnking)
- [ ] sandbox (GTA) (Origin: #45) (@rwarnking)
- [ ] arcade (Origin: #45) (@ArielMant0)

## Problems

- [ ] can not tag Scribblenauts mechanic (@ArielMant0) (problematic games)
- [ ] gamename Event[0] (@rwarnking) (technical problem)

**Comment by HendrikBrueckler** [comment]
Highscore/timetrial as replayability leaf seems reasonable. Possible alternative: tagging these as "competitive" but that feels wrong.

**Comment by rwarnking** [comment]
- Delete high replayvalue
- rename personal challenges todo tag to -> pc: other
- is money a material or a consumable
- difference between mng: units and compose team (prison architect - workforce, plants vs zombies)
- top: monsters und top: creatures mergen? obra dinn, minecraft
- should a topic be explicitly mentioned? minecraft, cosmoteer (economy)
- mass effect is an alternate reality also future?
- mechanic: stealth (gothic vs hitman)
- mng: money since almost every game has money (mng consumables)
- dorfromantik card game but no randomness
- what about consumable skills (geometry wars)
- no mechanics: (geometry wars)
- respawning enemies (sacred) mechanic
- goc: none, reach endpoint roller coaster
- topic revenge or similar (mirrors edge)
- ingame visual markers (jumping mirrors edge)
- gather information: exploration -> does this require the player to actually use the information for something (mirrors edge)
- every game is trial and error - how to differentiate
- gone home linear or open
- vio: enact is a problem solving technique while stealth is a mechanic, arent both both?
- geometry wars 3 - goc: death and package wise? homogen or heterogen?
- super meat boy
- random event frostpunk

---

bugs

- evidence with already deleted tags is shown
- selecting a whole category of tags is non revertable
- closing tag window does not reset tags
- sort evidence differently? ba name for example
- externalization definition
- externalization treemap has undefined

**Comment by ArielMant0** [comment]
fixed bugs
