### ISSUE TITLE
❔ Miscellaneous

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/github-importer-test#61]
<div align='justify'>This is a collection issue for all types of tasks. Here we will collect tagging ideas that are not yet relevant enough to varant a whole issue.</div>

## Potential New Tags and Issues

- [ ] Aussichtspunkte (might be part of motivations) (@rwarnking)
- [ ] level editor (@rwarnking)
- [ ] mod support (@rwarnking)
- [ ] bonuslevel (plants vs zombies, super meat boy) (Origin: #45) (@rwarnking)
- [ ] sandbox (GTA) (Origin: #45) (@rwarnking)
- [ ] arcade (Origin: #45) (@ArielMant0)

## Open tasks

- [ ] Rework point and click (input functionality)

## Problems

- [ ] can not tag Scribblenauts mechanic (ArielMant0) (problematic games)
- [ ] gamename Event[0] (@rwarnking) (technical problem)
